;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		cua-scroll-down
		cua-scroll-up
		evil-append
		evil-append-line
		evil-backward-char
		evil-delete
		evil-digit-argument-or-evil-beginning-of-line
		evil-end-of-line
		evil-forward-char
		evil-insert
		evil-insert-line
		evil-next-line
		evil-normal-state
		evil-previous-line
		evil-scroll-line-down
		evil-snipe-s
		evil-visual-char
		evil-yank
		))

(setq mc/cmds-to-run-once
      '(
		))
