;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		evil-backward-char
		evil-delete-char
		evil-digit-argument-or-evil-beginning-of-line
		evil-forward-char
		evil-replace
		))

(setq mc/cmds-to-run-once
      '(
		))
