;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-backward-word-begin
        evil-delete-char
        evil-digit-argument-or-evil-beginning-of-line
        evil-emacs-state
        evil-exit-emacs-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-replace
        ))

(setq mc/cmds-to-run-once
      '(
        ))
